### ISSUE TITLE
Firefox in dark mode can't show documentation correctly

### ISSUE THREAD

**Issue by acomagu** [logseq/plugins#6]
When user uses dark theme, the contrast of text is too low.

![image](https://user-images.githubusercontent.com/1362750/230552533-08b941f1-4af5-4a3b-b67b-d526b079c4d0.png)

This line seems the direct cause.

https://github.com/logseq/plugins/blob/f1e96bb6e93227c41a1d9dbed5bf236189935d68/docs/components/Description.tsx#L120

Changing this value to `dark` fixes the problem(at least Firefox in Dark Mode).

I don't know why Chrome can render properly but Firefox can't(Firefox bug? Or Chrome bug?).

Firefox 111.0.1

Thank you!

**Comment by joodo** [comment]
Still got problem on 129.0.1 
![Snipaste_2024-08-27_19-39-35](https://github.com/user-attachments/assets/bf04da10-a66b-419a-9192-b6cf28ecf48c)
